Spring cloud : Archetype
========================

|========================================
|Date|Version|Author|Comment
|may-2016|1.0|M. Dhalluin|Init
|may-2016|1.0|B. Coulaud|Init
|========================================

IMPORTANT: The using Spring Cloud version for this project is *Brixton.M4*

Introduction
------------

This project is a simple example of Spring Cloud implementation using Redis shared session

*Enjoy it* and contact us if you need help !!!

Maven configuration
-------------------

Getting started
---------------

=== Prerequisites :


Install the following tools in order to run the project.

- link:http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[JDK8]
- link:https://maven.apache.org/download.cgi[MAVEN]
- link:https://www.mongodb.com/download-center?jmp=nav#community[MONGODB]
- link:https://github.com/MSOpenTech/redis/releases[REDIS]

=== Get the project :

git clone https://github.com/maxiplay/SpringCloudRedisSessionExample

=== Go to the project root folder and :

Install the parent project
----
mvn install -f parent-project/
----
Build the authentication dependency
----
mvn install -f auth-redis-based/
----
Install the micro-service common dependency
----
mvn install -f common/
----
Build and start the registry server
----
mvn install -f registry-server/ && java -jar registry-server/target/registry-server-0.0.1-SNAPSHOT.jar
----
Build and start the book micro-service example
----
mvn install -f book-ms/ && java -jar book-ms/target/book-ms-0.0.1-SNAPSHOT.jar
----
Build and start the zuul proxy
----
mvn install -f gateway/ && java -jar gateway/target/gateway-0.0.1-SNAPSHOT.jar
----

=== Go to the project root folder and inject data into database :
----
mongoimport --db test --collection docs --file resources/datas/book.json
mongoimport --db test --collection docs --file resources/datas/user.json
----
=== Open you browser and navigate to http://localhost:7080 +

Now you have a micro-service architecture with a registry server (registry-server), a Zuul proxy (gateway), a micro-service example (book-ms). +

The webapp contained in the gateway is able to list books from the book-ms microservice and to provide a UI in order to authenticate to the platform.

IMPORTANT: If Redis shared session works fine, you should have the list of books displayed. If not, verify the ajax request to get book (401 error if Redis shared session does not work)
